---
# handlers file for Promtail
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
    name: promtail
  become: true

- name: restart promtail
  ansible.builtin.service:
    name: promtail
    state: restarted
  become: true
